DROP TABLE IF EXISTS votes;
DROP TABLE IF EXISTS ballots;
DROP TABLE IF EXISTS invitations;
DROP TABLE IF EXISTS choices;
DROP TABLE IF EXISTS questions;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS decisions;